# Alert/Effects Resources Translations
ADDITIONAL_SERVICE: 'an additional service'
AMBER_ALERT: 'an amber alert'
BIKE_ISSUE: 'a bike issue'
CANCELLATION: 'a cancellation'
DELAY: 'a delay'
DETOUR: 'a detour'
DOCK_CLOSURE: 'a dock closure'
DOCK_ISSUE: 'a dock issue'
ELEVATOR_CLOSURE: 'an elevator closure'
ESCALATOR_CLOSURE: 'an escalator closure'
EXTRA_SERVICE: 'extra service'
FACILITY_ISSUE: 'a facility issue'
MODIFIED_SERVICE: 'a modified service'
NO_SERVICE: 'no service'
OTHER_EFFECT: 'another effect'
PARKING_CLOSURE: 'a parking closure'
PARKING_ISSUE: 'a parking issue'
POLICY_CHANGE: 'a policy change'
SCHEDULE_CHANGE: 'a schedule change'
SERVICE_CHANGE: 'a service change'
SHUTTLE: 'a shuttle'
SNOW_ROUTE: 'a snow route'
STATION_CLOSURE: 'a station closure'
STATION_ISSUE: 'a station issue'
STOP_CLOSURE: 'a stop closure'
STOP_MOVE: 'a stop move'
STOP_MOVED: 'a stop moved'
SUMMARY: 'a summary'
SUSPENSION: 'a suspension'
TRACK_CHANGE: 'a track change'
UNKNOWN_EFFECT: 'an unknown effect'

# Cause Translations
ACCIDENT: 'accident'
AMTRAK: 'amtrak'
AN_EARLIER_MECHANICAL_PROBLEM: 'an earlier mechanical problem'
AN_EARLIER_SIGNAL_PROBLEM: 'an earlier signal problem'
AUTOS_IMPEDING_SERVICE: 'autos impeding service'
COAST_GUARD_RESTRICTION: 'coast guard restriction'
CONGESTION: 'congestion'
CONSTRUCTION: 'construction'
CROSSING_MALFUNCTION: 'a crossing malfunction'
DEMONSTRATION: 'a demonstration'
DISABLED_BUS: 'a disabled bus'
DISABLED_TRAIN: 'a disabled train'
DRAWBRIDGE_BEING_RAISED: 'a drawbridge being raised'
ELECTRICAL_WORK: 'electrical work'
FIRE: 'a fire'
FOG: 'fog'
FREIGHT_TRAIN_INTERFERENCE: 'a freight train interference'
HAZMAT_CONDITION: 'a hazmat condition'
HEAVY_RIDERSHIP: 'heavy ridership'
HIGH_WINDS: 'high winds'
HOLIDAY: 'the holidays'
HURRICANE: 'a hurricane'
ICE_IN_HARBOR: 'ice in the harbor'
MAINTENANCE: 'maintenance'
MECHANICAL_PROBLEM: 'a mechanical problem'
MEDICAL_EMERGENCY: 'a medical emergency'
PARADE: 'a parade'
POLICE_ACTION: 'police action'
POWER_PROBLEM: 'a power problem'
SEVERE_WEATHER: 'severe weather'
SIGNAL_PROBLEM: 'a signal problem'
SLIPPERY_RAIL: 'a slippery rail'
SNOW: 'snow'
SPECIAL_EVENT: 'a special event'
SPEED_RESTRICTION: 'a speed restriction'
SWITCH_PROBLEM: 'a switch problem'
TIE_REPLACEMENT: 'a tie replacement'
TRACK_PROBLEM: 'a track problem'
TRACK_WORK: 'track work'
TRAFFIC: 'traffic'
UNRULY_PASSENGER: 'an unruly passenger'
UNKNOWN_CAUSE: 'an unknown cause'
WEATHER: 'weather'